name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with Buildozer
      run: |
        buildozer android debug

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: video-player-apk
        path: bin/*.apk
